import ClientProvider from "./ClientProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientProvider>

          {children}

          <Toaster
            position="top-right"
            reverseOrder={false}
            containerStyle={{top: 80}}/>
            
        </ClientProvider>
      </body>
    </html>
  );
}
